[package]
name = "xone-battery"
version = "0.1.0"
authors = ["Kim Sevandersson<ksevandersson@gmail.com>"]

[dependencies.winapi]
version = "0.2.8"

[dependencies.xinput-sys]
version = "0.2.0"

[dependencies.user32-sys]
version = "0.2.0"

[dependencies.comctl32-sys]
version = "0.2.0"

[dependencies.kernel32-sys]
version = "0.2.2"